import Link from "next/link";
import { publicPageMetadata } from "@/lib/site";
import { getSchool } from "@/lib/schools-server";
import BetaNotice from "@/components/site/BetaNotice";
export const metadata = publicPageMetadata({ title: "Write for The Daily Byte", description: "Share original stories about news, campus life, tech and culture. Build your byline with editorial review at The Daily Byte.", path: "/write" });
export default async function WritePage({ searchParams }: { searchParams: Promise<{ school?: string | string[] }> }) {
  const slug = (await searchParams).school;
  const school = typeof slug === "string" && /^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug) && slug.length <= 180 ? await getSchool(slug) : null;
  const primary = "inline-flex min-h-11 items-center justify-center rounded-full bg-ink px-6 py-3 text-sm font-semibold text-white hover:bg-brand";
  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 sm:py-14 [overflow-wrap:anywhere]">
    <header className="mb-10"><p className="text-sm font-bold text-brand">Your perspective belongs in the conversation</p><h1 className="mt-3 font-display text-4xl font-bold sm:text-5xl">Write for The Daily Byte</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-muted">A digital publication for news, tech, culture and the stories shaping student life. Bring an original idea, a curious mind and a willingness to work with an editor.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/signup" className={primary}>Create a contributor account</Link><Link href="/dashboard/articles/new" className="inline-flex min-h-11 items-center rounded-full border border-line px-6 py-3 text-sm font-semibold hover:text-brand">Already a contributor? Start writing</Link></div></header>
    <BetaNotice />
    {school && <section className="mt-8 rounded-3xl border border-line bg-surface p-6"><h2 className="font-display text-xl font-bold">Write about {school.name}</h2><p className="mt-3 text-sm leading-relaxed text-muted">After signing in, choose your school in your profile if it applies to you. You can also select a campus for an individual story, or leave it as a general story. This is a community connection, not a school partnership.</p><Link href="/dashboard/profile" className="mt-3 inline-flex min-h-11 items-center font-semibold text-accent hover:underline">Set up your profile and school</Link></section>}
    <div className="mt-10 grid gap-6 md:grid-cols-2">
      <section className="rounded-3xl border border-line p-6"><h2 className="font-display text-2xl font-bold">Who can contribute?</h2><p className="mt-4 leading-relaxed text-muted">Students, emerging writers and curious contributors with something useful to report or explain. You do not need a school affiliation. Start with a topic you know, and support your claims with sources.</p></section>
      <section className="rounded-3xl border border-line p-6"><h2 className="font-display text-2xl font-bold">What can you write?</h2><p className="mt-4 leading-relaxed text-muted">Campus life, technology, culture, entertainment, business, sports, politics and everyday issues. We welcome reporting, explainers, interviews, features and clearly identified opinion pieces.</p></section>
    </div>
    <section className="mt-10"><h2 className="font-display text-2xl font-bold">From an idea to a published story</h2><ol className="mt-5 grid gap-5 sm:grid-cols-3">{[["Set up your byline", "Create an account, add a short bio and optionally choose your school."], ["Write and submit", "Draft an original story, credit sources and submit it for editorial review."], ["Work with an editor", "Editors may request changes, approve or decline a submission. Approved stories are published or scheduled by the editorial team."]].map(([title, text], index) => <li key={title} className="min-w-0 rounded-2xl bg-surface p-5"><p className="text-sm font-bold text-brand">0{index + 1}</p><h3 className="mt-2 font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted">{text}</p></li>)}</ol></section>
    <section className="mt-10 max-w-3xl"><h2 className="font-display text-2xl font-bold">Build a body of work</h2><p className="mt-4 leading-relaxed text-muted">Published stories carry your byline and give you links to share in your portfolio. Practice reporting, develop your voice and learn through editorial feedback. Publication is not guaranteed.</p><p className="mt-4 leading-relaxed text-muted">Contributing is voluntary and unpaid unless a separate arrangement explicitly says otherwise. Do not submit work you do not have permission to publish, private personal information, or unsupported allegations.</p></section>
    <section className="mt-10 rounded-3xl border border-line p-6"><h2 className="font-display text-xl font-bold">Explore the campus community</h2><p className="mt-3 text-sm leading-relaxed text-muted">Explore stories connected to Olabisi Onabanjo University (OOU). This is an independent community initiative, not an official university partnership.</p><div className="mt-3 flex flex-wrap gap-4"><Link href="/schools/olabisi-onabanjo-university" className="inline-flex min-h-11 items-center font-semibold text-accent hover:underline">Explore OOU stories</Link><Link href="/feedback" className="inline-flex min-h-11 items-center font-semibold hover:underline">Send feedback</Link></div></section>
  </div>;
}
